// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sibsipfurmgtxmxbbzem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpYnNpcGZ1cm1ndHhteGJiemVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjYwNDksImV4cCI6MjA2Mzg0MjA0OX0.InGEnRnC_IaPye0z87bHSkahxXjfl94jT9uQSg5QL2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);